name: flutter_multi_child_animated_switcher
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/Iconica-Development/flutter_multi_child_animated_switcher

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
